<a href="https://colab.research.google.com/github/KM-Pusat/TensorFlow_Learning_KMP/blob/main/01_KMP_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 01. Getting started with TensorFlow: Panduan untuk memahami fundamental TensorFlow

## Apa itu TensorFlow?

[TensorFlow](https://www.tensorflow.org/) adalah open-source end-to-end library machine learning  untuk memproses data (**preprocessing data**), membuat model (**modelling data**) dan menyajikan model (**memberikan model yang sudah di buat ke client atau orang lain**).

## Mengapa menggunakan TensorFlow?

Jika dibandingkan dengan membuat model machine learing dan deep learning dari awal, jauh lebih cepat dan mudah jika kita menggunakan library python seperti TensorFlow. Hal ini dikarenakan TensorFlow banyak memuat fungsi machine learning yang paling umum digunakan.

## Apa yang akan dibahas

TensorFlow sangatlah luas. Namun premisnya sangat simpel: mengubah data menjadi angka (**tensors**) dan membuat algoritma machine learning untuk menemukan pola dari **tensor** tersebut.

Di dalam notebook (hands-on) ini kita akan membahas beberapa operasi paling dasar (Fundamental) dalam operasi TensorFlow, lebih spesifiknya:
* Pengertian apa itu tensor (membuat tensors)
* Mendapatkan informasi dari tensor (atribut tensor)
* Memanipulasi tensor (operasi TensorFlow)
* Tensors dan NumPy
* Menggunakan @tf.function (cara untuk meningkatkan kecepatan eksekusi program fungsi suatu Python)
* Menggunakan GPUs dengan TensorFlow
* Latihan

Catatan:
* Banyak sekali kode yang akan dieksekusi akan otomatis berkerja di balik layar (ketika membuat model) tapi layak untuk diketahui sehingga jika kalian melihat salah satu dari hal-hal ini, Kalian tahu apa yang terjadi.
* Untuk semua fungsi TensorFlow yang kalian lihat, akan sangat penting untuk melihat dan mengecek dokumentasi, sebagai contoh, pergi ke Python API docs untuk semua fungsi dan cari apa saja yang kamu perlukan: https://www.tensorflow.org/api_docs/python/ (jangan khawatir memang agak budreg di awal, tetapi dengan latihan yang cukup, kalian akan terbiasa menavigasi dokumentasi tersebut).

In [ ]:
# Create timestamp
import datetime

print(f"Notebook terkahir dijalankan (end-to-end): {datetime.datetime.now()}")

Notebook terkahir dijalankan (end-to-end): 2023-05-24 10:15:35.604079


## Pengertian apa itu Tensors

Jika kalian pernah menggunakan NumPy, [tensors](https://www.tensorflow.org/guide/tensor) hampir seperti NumPy arrays (kita akan melihatnya nanti).

Untuk memahami notebook (hands-on) dan kedepannya, kalian dapat membayangkan tensor sebagai sebuah multi-dimensional numerical representation (juga dapat disebut sebagai n-dimensional, dimana n dapat berupa angka berapapun) dari sesuatu. Yang dimana sesuatu tersebut dapat berupa apa saja yang dapat kalian bayangkan:
* Bisa saja dapat berupa angka itu sendiri (menggunakan tensor untuk mewakili harga rumah).
* Bisa saja berupa gambar (menggunakan tensors untuk mewakili pixels suatu gambar).
* Bisa saja berupa teks (menggunakan tensor untuk mewakili kata).
* Atau bisa saja berupa bentuk lain dari suatu informasi (atau data) yang ingin kalian wakilkan dengan angka.

Perbedaan paling mendasar dari tensor dan NumPy arrays (juga merupakan n-dimensional array of numbers) adalah tensor dapat mengambil resource (dieksekusi) dari [GPUs (graphical processing units)](https://blogs.nvidia.com/blog/2009/12/16/whats-the-difference-between-a-cpu-and-a-gpu/) dan [TPUs (tensor processing units)](https://en.wikipedia.org/wiki/Tensor_processing_unit).

Keuntungan yang didapatkan jika dapat dijalankan dengan GPUs dan TPUs adalah komputasi atau perhitungan yang jauh lebih cepat, ini berarti, jika kita ingin menemukan pola dalam representasi numerical dari data kita, kita dapat menemukannya dengan lebih cepat jika menggunakan GPUs dan TPUs.

Okay, kita sudah cukup banyak berbicara tentang tensor, sekarang mari kita ngoding.

Hal pertama yang harus dilakukan adalah mengimport TensorFlow yang biasanya dialiaskan dengan `tf`.

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__) # menampilkan versi TensorFlow

2.12.0


### Membuat tensor dengan `tf.constant()`

Seperti yang sudah dijelaskan sebelumnya, umumnya kaliian tidak selalu membuat tensors sendiri. Hal ini karena TensorFlow memiliki modul bawaan (modules built-in) (seperti [`tf.io`](https://www.tensorflow.org/api_docs/python/tf/io) dan [`tf.data`](https://www.tensorflow.org/guide/data)) yang mampu membaca sumber data dan otomatis mengkonversinya kedalam bentuk tensor dan seterusnya, neural network models akan memperosesnya untuk kita.

Namun untuk sekarang, karena kita sedang berkenalan dan agar lebih familiar dengan tensor serta bagaimana memanipulasi tensor, kita akan melihat bagaimana kita akan membuatnya.

Kita akan memulainya dengan [`tf.constant()`](https://www.tensorflow.org/api_docs/python/tf/constant).

In [ ]:
# Membuat skalar (rank 0 tensor)
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

Scalar biasanya juga disebut sebagai rank 0 tensor. Karena tidak memiliki dimensi (Ini hanyalah sebuah angka).

> 🔑 **Catatan:** Untuk sekarang, kalian tidak perlu tahu banyak tentang perbedaan rank dalam suatu tensor (namun kita akan melihat dan memahaminya nanti). Poin penting yang harus diketahui adalah jika tensor dapat memiliki rentang dimensi (range of dimensions) yang unlimited (nilai tepatnya tergantung dari data apa yang kalian wakilkan).

In [ ]:
# Mengecek nomor dimensi suatu tensor (ndim artinya adalah number of dimensions)
scalar.ndim

0

In [ ]:
# Membuat vektor (lebih dari 0 dimensions)
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Mengecek nomor dimensi dari vektor tensor kita
vector.ndim

1

In [ ]:
# Membuat matriks (lebih dari 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# Mengecek nomor dimensi dari matriks tensor kita
matrix.ndim

2

Secara default, TensorFlow membuat tensors dengan tipe data `int32` atau `float32`.

Hal ini juga dikenal sebagai [32-bit precision](https://en.wikipedia.org/wiki/Precision_(computer_science) (semakin besar angkanya, semakin presisi hasil model TensorFlow yang dibuat, dan semakin banyak memori yang digunakan dalam komputer).

In [ ]:
# Membuat matriks lain dan mendefinisikan tipe datanya
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # mengspesifikkan tipe data dengan argumen 'dtype'
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# Meskipun another_matrix mengandung lebih banyak angka, namun dimensinya masih sama
another_matrix.ndim

2

In [ ]:
# Bagaimana dengan tensor? (lebih dari 2 dimensi, meskipun semua yang diatas tadi juga termasuk tensor)
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

Hal ini juga dikenal sebagai rank 3 tensor (3-dimensions), namun tensor juga dapat memiliki jumlah dimensi yang arbitrary (tak-terbatas).

Sebagai contoh, kalian ingin mengubah suatu gambar menjadi tensor dengan shape (224, 224, 3, 32), dimana:
* 224, 224 (the first 2 dimensions) adalah tinggi dan lebar suatu pixels pada gambar.
* 3 angka untuk colour channels dari gambar RGB (red, green blue).
* 32 adalah angka untul batch size (jumlah gambar yang dilihat oleh neural network pada satu waktu).

Semua yang sudah dibuat diatas sebenarnya adalah tensor. Namun kamu juga memanggilnya sesuai dengan nama yang berbeda beda (tergantung dari nama yang diberikan):
* **scalar**: suatu nomor atau angka.
* **vector**: angka yang memiliki arah dan  (Contoh : kecepatan angin dan arahnya).
* **matrix**: suatu 2-dimensional array dari angka.
* **tensor**: suatu n-dimensional array dari angka (dimana n dapat berupa angka berapa saja, 0-dimension tensor bisa juga disebut scalar, dan 1-dimension tensor bisa juga disebut vektor).

Terkadang yang membuat bingung adalah, istilah matriks dan tensor sering digunakan secara bergantian.

Untuk kedepannya karena menggunakan TensorFlow, semua yang kita rujuk dan gunakan akan menjadi tensor.

Untuk selengkapnya memahami perbedaan skalar (**scalars**), vectors (**vektor**) dan matriks (**matrices**) secara matematika, kalian dapat melihatnya di [visual algebra post by Math is Fun](https://www.mathsisfun.com/algebra/scalar-vector-matrix.html).

![difference between scalar, vector, matrix, tensor](https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)

### Membuat tensor dengan `tf.Variable()`

kalian juga bisa (meskipun kalian akan jarang menggunakannya, karena sering kali saat nanti bekerja dengan data. tensor akan dibuat untuk kalian secara otomatis) membuat tensor dengan [`tf.Variable()`](https://www.tensorflow.org/api_docs/python/tf/Variable).

Perbedaan antara `tf.Variable()` dan `tf.constant()` adalah tensors yang dibuat dengan `tf.constant()` tidak dapat diubah (tidak dapat diganti, dan hanya dapat digunakan ketika membuat tensor baru), sebaliknya, tensors yang dibuat dengan `tf.Variable()` dapat diubah (dapat diganti datanya).

In [ ]:
# Membuat tensor yang sama dengan tf.Variable() dan tf.constant()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

Sekarang kita akan mengganti salah satu elemen dari changeable_tensor.

In [ ]:
# Akan menghasilkan error (karena membutuhkan .assign() method)
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

Untuk mengubah elemen dari `tf.Variable()` tensor membutuhkan `assign()` method.

In [ ]:
# Tidak akan error
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

Sekarang kita akan mencoba mengubah nilai dari `tf.constant()` tensor.

In [ ]:
# Akan error (karena tidak dapat mengubah nilai tf.constant())
unchangeable_tensor[0].assign(7)
unchangleable_tensor

AttributeError: ignored

Lantas yang mana yang harusnya digunakan? `tf.constant()` atau `tf.Variable()`?

Ini tergantung dari apa yang menjadi kebutuhan permasalahan. Namun, kebanyakan waktu sekarang, TensorFlow akan otomatis memilihkannya untuk kalian (ketika sedang memuat data atau memodeling data).

### Membuat tensor random

Random tensors adalah tensors yang terdiri dari beberapa ukuran abitary dan berisi angka acak.

Mengapa kalian ingin membuat random tensor?

Karena inilah yang digunakan oleh neural network untuk menginisiasi weight (patterns) yang digunakan untuk mempelajari data.

Sebagai contoh, proses pembelajaran neural network sering kali melibatkan pengambilan susunan angka acak n-dimensional array dan menyempurnakannya hingga mewakili semacam pola (cara ringkas untuk merepresentasikan data original).

**Bagaimana neural network belajar**
![how a network learns](https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-how-a-network-learns.png)
*Network belajar dengan memulai membuat pola acak (1) selanjutnya membuat contoh demonstrasi dari data tersebut (2) ketika memperbaharui pola, pola acak tersebut akan mewakili contoh (3).*

Kita dapat membuat tensor random dengan menggunakan [`tf.random.Generator`](https://www.tensorflow.org/guide/random_numbers#the_tfrandomgenerator_class) class.

In [ ]:
# Membuat dua random (namun sama) tensors
random_1 = tf.random.Generator.from_seed(42) # mengatur seed untuk reproduktifitas
random_1 = random_1.normal(shape=(3, 2)) # membuat tensor dengan normal distribution
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Apakah mereka sama?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

Dari random tensor yang kita buat, hal itu sebenarnya adalah [pseudorandom numbers](https://www.computerhope.com/jargon/p/pseudo-random.htm) (mereka terlihat acak namun sebenarnya tidak).

Jika kita mendefinisikan seed, maka kita akan mendapatkan angka random yang sama (jika kalian pernah menggunakan library NumPy, method tersebut hampir sama dengan `np.random.seed(42)`).

Mengatur seed hampir sama dengan mengatakan, "hey, buatkan beberapa angka acak, tapi bentuknya sama dengan X" (X adalah seed).

Apa yang akan terjadi jika kita mengubah seed tersebut?

In [ ]:
# membuat dua random (dan berbeda) tensors
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2))
random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal(shape=(3, 2))

# Mengecek tensor tersebut dan bandingkan apakah mereka sama
random_3, random_4, random_1 == random_3, random_3 == random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.2730574 , -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.2829171 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

Lalu bagaimana jika kita ingin mengocok urutan tensor tersebut?

Tunggu, mengapa kita melakukannya?

Anggap saja jika kita bekerja dengan 15,000 gambar kucing dan anjing, 10,000 gambar pertama adalah kucing dan 5,000 gambar berikutnya adalah anjing. Urutan ini dapat mempengaruhi cara neural network belajar (mungkin cocok dengan mempelajari urutan data), sebagai gantinya, jauh lebih baik dengan  memindahkan data anda.

In [ ]:
# Mengacak tensor (berguna saat kalian ingin mengacak data kalian)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Mendapatkan hasil yang berbeda setiap kali blok kode dijalankan
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# Mengacak tensor dalam urutan yang sama setiap menggunakan parameter seed (masih belum sama setiap kali blok di run)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

Tunggu... mengapa angka yang keluar tidak sama?

Hal ini dikarenakan oleh aturan #4 dari [`tf.random.set_seed()`](https://www.tensorflow.org/api_docs/python/tf/random/set_seed) documentation.

> "4. Jika global seed dan operation seed ditetapkan. Kedua seed yang digunakan bersama untuk menentukan random sequence (*urutan acak*)."

`tf.random.set_seed(42)` mendefinisikan global seed, dan `seed` parameter di `tf.random.shuffle(seed=42)` mendefinisikan operation seed.

Karena, "Operasi yang mengandalkan random seed sebenarnya berasal dari dua seed: global seed and operation-level seed. Ini untuk menetapkan global seed."

In [ ]:
# Mengacak dalam urutan yang sama setiap saat

# Mendefinisikan global random seed
tf.random.set_seed(42)

# Mendefinisikan operation random seed
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# Mendefinisikan global random seed
tf.random.set_seed(42) # jika kalian block comment kode ini, kalian akan mendapatkan hasil yang berbeda

# Mendefinisikan operation random seed
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

### Cara lain untuk membuat tensor

Meskipun kalian mungkin jarang menggunakan ini (ingat, banyak tensor operations berkerja di balik layar untuk kalian), kalian bisa menggunakan [`tf.ones()`](https://www.tensorflow.org/api_docs/python/tf/ones) untuk membuat tensor of all ones (tensor dengan isi elemennya = 1) dan [`tf.zeros()`](https://www.tensorflow.org/api_docs/python/tf/zeros) untuk membuat tensor of all zeros (tensor dengan isi elemennya = 0).

In [ ]:
# Membuat sebuah tensor of all ones (semua elemennya = 1)
tf.ones(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
# Membuat sebuah tensor of all zeros (semua elemennya = 0)
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

Kalian juga dapat mengubah NumPy arrays menjadi bentuk tensor.

Ingat, perbedaan paling dasar antara tensor dan NumPy arrays adalah tensor dapat dijalankan dengan menggunakan resource GPUs.

> 🔑 **Catatan:** Matriks atau tensor biasanya diwakilkan oleh huruf kapital (Contohnya : `X` atau `A`) yang dimana biasanya vektor akan diwakili oleh huruf kecil (Contohnya : `y` atau `b`).

In [ ]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # Membuat NumPy array antara 1 dan 25
A = tf.constant(numpy_A,
                shape=[2, 4, 3]) # catatan: total shape (2*4*3) harus sesuai dengan jumlah elemen dalam array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

## Mendapatkan informasi dari tensor (shape, rank, size)

Akan ada saatnya nanti kalian ingin mendapatkan potongan informasi yang berbeda dari tensor kalian, khususnya, kalian mungkin harus mengetahui kosakata tensor berikut:
* **Shape:** Panjang (jumlah elemen) dari setiap dimensi tensor.
* **Rank:** Jumlah dimensi tensor. Skalar memiliki rank 0, vector memiliki rank 1, matrix memiliki rank 2, dan tensor memiliki rank-n.
* **Axis** atau **Dimension:** Suatu dimensi tensor tertentu.
* **Size:** Jumlah total item dalam tensor.

Kalian akan menggunakan ini terutama saat kalian mencoba mensejajarkan shape data kalian. Misalnya, memastikan bentuk tensor gambar kalian sama dengan bentuk lapisan input model kalian.

Kita telah melihat salah satunya sebelum menggunakan `ndim` attribute. Sekarang mari lihat sisanya.

In [ ]:
# Membuat sebuah rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Mendapatkan bermacam-macam atribut tensor
print("Tipe data dari setiap elemen:", rank_4_tensor.dtype)
print("Ukuran dimensi (rank):", rank_4_tensor.ndim)
print("Bentuk tensor (shapes):", rank_4_tensor.shape)
print("Elemen sepanjang sumbu 0 dari indexing:", rank_4_tensor.shape[0])
print("Elements sepanjang sumbu akhir dari indexing:", rank_4_tensor.shape[-1])
print("Total angka elemennya (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() mengubahnya ke NumPy array

Tipe data dari setiap elemen: <dtype: 'float32'>
Ukuran dimensi (rank): 4
Bentuk tensor (shapes): (2, 3, 4, 5)
Elemen sepanjang sumbu 0 dari indexing: 2
Elements sepanjang sumbu akhir dari indexing: 5
Total angka elemennya (2*3*4*5): 120


Kalian juga bisa melakukan index tensors sama seperti list pada Python.

In [ ]:
# Mendapatkan 2 items pertama dari setiap dimensi
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Mendapatkan dimensi dari setiap index kecuali untuk yang terakhir
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Membuat rank 2 tensor (2 dimensi)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Mendapatkan item terakhir dari setiap baris
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

Kalian juga bisa menambahkan dimensions ke tensor kalian sambil menjaga informasi yang ditampilkan tetap sama `tf.newaxis`.

In [ ]:
# Menambahkan dimension extra (di akhir)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # dalam Python  "..." berarti "semua dimensi sebelumnya"
rank_2_tensor, rank_3_tensor # shape (2, 2), shape (2, 2, 1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

Kalian juga bisa menggunakan [`tf.expand_dims()`](https://www.tensorflow.org/api_docs/python/tf/expand_dims) untuk menambahkan dimensions ke tensor kalian.

In [ ]:
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" berarti sumbu (axis) terakhir

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

## Memanipulasi tensors (tensor operations)

Menemukan pola dalam tensor (numberical representation of data) membuat kira perlu memanipulasi tensor tersebut.

Sekali lagi, saat membuat model dengan TensorFlow, sebagian besar menemukan pola ini dilakukan dibalik layar untuk kalian.

### Basic operations (Operasi Dasar)

Kalian bisa melakukan banyak operasi matematika dasar langsung pada tensor menggunakan operator Python seperti, `+`, `-`, `*`.

In [ ]:
# Kalian juga dapat menambahkan nilai (menjumlahkan) ke tensor menggunakan addition operator (operator penjumlahan)
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

Semenjak kita menggunakan `tf.constant()`, tensor yang sudah dibuat tersebut tidak dapat diubah (penambahan dilakukan pada salinan).

In [ ]:
# Original tensor tidak berubah
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

Operator lain juga bekerja.

In [ ]:
# Perkalian (atau yang dikenal sebagai element-wise multiplication)
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# Pengurangan
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

Kalian juga dapat menggunakan fungsi  TensorFlow yang setara. Menggunakan fungsi TensorFlow (jika memungkinkan) memiliki keuntungan yaitu proses dapat dipercepat nanti saat dijalankan sebagai bagian dari [TensorFlow graph](https://www.tensorflow.org/tensorboard/graphs).

In [ ]:
# Menggunakan fungsi tensorflow yang setara dengan '*' (operator perkalian)
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# tensor asli (bawaannya) masih tidak berubah
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

### Matrix mutliplication (perkalian matriks)

Salah satu operasi yang paling umum dilakukan dalam algoritma machine learning adalah [matrix multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

TensorFlow mengimplementasikan fungsionalitas perkalian matriks ini dengan menggunakan method [`tf.matmul()`](https://www.tensorflow.org/api_docs/python/tf/linalg/matmul).

Dua aturan utama dalam perkalian matriks yang perlu kalian ingat adalah:
1. Inner dimensions (dimensi bagian dalam) haruslah cocok:
  * `(3, 5) @ (3, 5)` akan tidak berhasil / bekerja
  * `(5, 3) @ (3, 5)` akan berhasil / bekerja
  * `(3, 5) @ (5, 3)` akan berhasil / bekerja
2. Matriks yang dihasilkan memiliki shape (bentuk) dari outer dimensions (dimensi luar):
 * `(5, 3) @ (3, 5)` -> `(5, 5)`
 * `(3, 5) @ (5, 3)` -> `(3, 3)`

> 🔑 **Note:** '`@`' di Python merupakan simbol untuk matrix multiplication (perkalian matriks).

In [ ]:
# Matrix multiplication (perkalian matriks) di TensorFlow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Matrix multiplication (perkalian matriks) dengan operator Python '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

Kedua contoh diatas dapat berfungsi karena variabel `tensor`kita memiliki shape (2, 2).

Lalu apa yang terjadi jika kita membuat beberapa tensor yang memiliki shape yang tidak sama?

In [ ]:
# Membuat tensor dengan shape (3, 2)
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Membuat tensor lain dengan shape (3, 2)
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Mencoba melakukan matrix multiply (perkalian matriks) kedua tensor tersebut (akan error)
X @ Y

InvalidArgumentError: ignored

mencoba melakukan matrix multiply terhadap dua tensors dengan shape `(3, 2)` akan menghasilkan error karena inner dimensions tidak cocok.

Maka dari itu kita juga perlu:
* Reshape (membentuk ulang) X ke `(2, 3)` sehingga menjadi `(2, 3) @ (3, 2)`.
* Reshape (membentuk ulang) Y ke `(3, 2)` sehingga menjadi `(3, 2) @ (2, 3)`.

Kita dapat melakukannya dengan cara:
* [`tf.reshape()`](https://www.tensorflow.org/api_docs/python/tf/reshape) - memungkinkan kita membentuk ulang (reshape) tensor menjadi bentuk yang ditentukan.
* [`tf.transpose()`](https://www.tensorflow.org/api_docs/python/tf/transpose) - mengubah dimensi tensor tertentu.

![lining up dimensions for dot products](https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-lining-up-dot-products.png)

Sekarang ayo kita mencoba method `tf.reshape()` terlebih dahulu.

In [ ]:
# Contoh reshape (3, 2) -> (2, 3)
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
# Mencoba melakukan matrix multiplication dengan reshaped Y
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

Itu berhasil, Sekarang ayo kita coba hal yang sama dengan reshaped `X`, namun sekarang kita akan menggunakan method [`tf.transpose()`](https://www.tensorflow.org/api_docs/python/tf/transpose) dan `tf.matmul()`.

In [ ]:
# Contoh transpose (3, 2) -> (2, 3)
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [ ]:
# Mencoba melakukan matrix multiplication dengan reshape X
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# Kalian juga bisa mendapatkan hasil yang sama dengan parameter
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

Pastikan untuk memperhatikan perbedaan bentuk yang dihasilkan saat mentranspose tensor `X` atau melakukan reshaping `Y`.

Karena menurut aturan ke-2 yang disebutkan di atas:
 * `(3, 2) @ (2, 3)` -> `(3, 3)` dapat berhasil dengan `X @ tf.reshape(Y, shape=(2, 3))`
 * `(2, 3) @ (3, 2)` -> `(2, 2)` dapat berhasil dengan `tf.matmul(tf.transpose(X), Y)`

Manipulasi data semacam ini adalah pengingat: jika kalian nantinya akan menghabiskan banyak waktu dalam machine learning dan bekerja dengan neural network reshaping data (dalam bentuk tensor) untuk memersiapkannya agar dapat digunakan dengan berbagai operasi (seperti memberi makan pada model).

### Dot product

Multiplying matrices (mengalikan matriks) satu dengan lainnya juga disebut sebagai dot product.

Kalian dapat melakukan operasi `tf.matmul()` menggunakan [`tf.tensordot()`](https://www.tensorflow.org/api_docs/python/tf/tensordot).

In [ ]:
# Melakukan dot product pada titik X and Y (memerlukan X yang ditranspose)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

Kalian mungkin memperhatikan bahwa meskipun berhasil menggunakan fungsi `reshape` dan `tranpose`, kalian mendapatkan hasil yang berbeda saat menggunakan keduanya.

Mari melihat contohnya, pertama dengan  `tf.transpose()` lalu dengan `tf.reshape()`.

In [ ]:
# Melakuakan matrix multiplication antara X dan Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# Melakukan matrix multiplication antara X dan Y (reshaped)
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

Hmm... mereka menghasilkan nilai yang berbeda.

Yang aneh karena ketika berurusan dengan  `Y` (adalah `(3x2)` matrix), reshaping (membentuk kembali) ke `(2, 3)` dan tranposing (mentransposenya) menghasilkan bentuk yang sama.

In [ ]:
# Mengecek shapes dari Y, reshaped Y dan tranposed Y
Y.shape, tf.reshape(Y, (2, 3)).shape, tf.transpose(Y).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

Namun memanggil fungsi `tf.reshape()` dan `tf.transpose()` pada `Y` tidak selalu menghasilkan nilai yang sama.

In [ ]:
# Mengecek nilai dari Y, reshape Y dan tranposed Y
print("Normal Y:")
print(Y, "\n") # "\n" untuk newline

print("Y reshaped menjadi (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped menjadi (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Seperti yang kalian lihat, outputs dari `tf.reshape()` dan `tf.transpose()` ketika dipanggil pada `Y`, meskipun mereka memiliki bentuk yang sama, hasilnya akan berbeda.

Hal ini dapat dijelaskan dengan default behaviour (perilaku bawaan) dari setiap method:
* [`tf.reshape()`](https://www.tensorflow.org/api_docs/python/tf/reshape) - mengubah bentuk tensor yang diberikan (pertama) lalu memasukan nilai agar muncul (dalam kasusnya, 7, 8, 9, 10, 11, 12).
* [`tf.transpose()`](https://www.tensorflow.org/api_docs/python/tf/transpose) - menukar urutan sumbu (axes), secara default last axis (sumbu terakhir) berubah menjadi yang pertama, namun urutannya dapat diubah menggunakan [`perm` parameter](https://www.tensorflow.org/api_docs/python/tf/transpose).

Jadi mana yang harus kita gunakan?

Sekali lagi, sebagian besar waktu menjalankan operasi (ketika perlu dijalankan, seperti selama training neural network, akan diimplementasikan langsung ke kalian).

Namun umumnya, setiap kali melakukan matrix multiplication (perkalian matriks) dan shapes dua matriks tidak sejajar, kalian akan transpose (bukan reshape) dengan tujuan untuk mensejajarkannya.

### Informasi matrix multiplication
* Jika kita transposed `Y`, hal itu akan direpresentasikan sebagai $\mathbf{Y}^\mathsf{T}$ (perhatikan huruf kapital T untuk tranpose).
* Dapatkan tampilan ilustratif matrix multiplication oleh [Math is Fun](https://www.mathsisfun.com/algebra/matrix-multiplying.html).
* Coba demo matrix multiplcation langsung: http://matrixmultiplication.xyz/ (yang ditampilkan dibawah).

![visual demo of matrix multiplication](https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-matrix-multiply-crop.gif)

### Mengubah tipe data tensor

Terkadang kalian perlu atau ingin mengubah tipe data default dari tensor yang sudah dibuat.

Hal ini biasa terjadi saat kalian ingin menghitung menggunakan tingkat presisi yang lebih rendah (Contohnya : 16-bit floating point numbers vs. 32-bit floating point numbers).

Komputasi dengan tingkat peresisi yang kurang berguna pada perangkat dengan kapasistas komputasi yang lebih sedikit seperti mobile (karena semakin sedikit bit, semakin sedikit penyimpanan atau memori yang dibutuhkan untuk komputasi).

Kalian bisa mengubah tipe data tensor dengan menggunakan [`tf.cast()`](https://www.tensorflow.org/api_docs/python/tf/cast).

In [ ]:
# Membuat tensor baru dengan default datatype-nya (float32)
B = tf.constant([1.7, 7.4])

# Membuat tensor baru dengan default datatype-nya (int32)
C = tf.constant([1, 7])
B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [ ]:
# Mengubahnya dari float32 menjadi float16 (namun mengurangi tingkat presisinya)
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [ ]:
# Mengubahnya dari int32 menjadi float32
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

### Mendapatkan absolute value (nilai mutlak)
Terkadang kalian menginginkan nilai mutlak (semua nilainya positif) pada elemen dalam tensor kalian.

Untuk melakukannya, kalian bisa menggunakan [`tf.abs()`](https://www.tensorflow.org/api_docs/python/tf/math/abs).

In [ ]:
# Membuat tensor dengan nilai negatif
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# Mendapatkan nilai mutlaknya
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

### Menemukan min, max, mean, dan sum (aggregation)

Kalian dapat dengan cepat melakukan agregasi (melakukan perhitungan pada seluruh tensor) tensors untuk menemukan hal-hal seperti nilai minimum, nilai maksimum, rata-rata dan jumlah semua elemen.

Untuk melakukannya, aggregation methods biasanya memiliki sintaks `reduce()_[action]`, seperti:
* [`tf.reduce_min()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_min) - untuk menemukan nilai minimum dalam suatu tensor.
* [`tf.reduce_max()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_max) - untuk menemukan nilai maksimum dalam suatu tensor (sangat berguna saat kalian ingin menemukan prediksi kemungkinan tertinggi / highest prediction probability).
* [`tf.reduce_mean()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_mean) - untuk menemukan nilai rata-rata dalam suatu tensor.
* [`tf.reduce_sum()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_sum) - untuk menemukan jumlah semua elemen dalam tensor.
* **Catatan:** biasanya masing-masing berada di dalam module `math`, Contohnya : `tf.math.reduce_min()` tetapi kalian juga dapat menggunakan alias `tf.reduce_min()`.

Mari kita lihat dengan mencobanya.

In [ ]:
# Membuat tensor dengan 50 nilai acak antara 0 dan 100
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([97,  7, 44, 43,  9, 56, 15, 45, 29, 50, 70, 35, 88,  2, 67, 55, 22,
       16,  5, 69, 64, 81, 38, 69,  0,  3,  0, 27, 83, 39, 16, 38, 20, 34,
       97, 52, 76, 60, 94, 97, 99,  1, 95,  1, 13, 61, 20, 24, 32, 70])>

In [ ]:
# Menemukan nilai minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# Menemukan nilai maksimum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
# Menemukan rata-rata
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=44>

In [ ]:
# Menemukan jumlah
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2228>

Kalian juga dapat menemukan standard deviation (standar deviasi) ([`tf.reduce_std()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_std)) dan variance ([`tf.reduce_variance()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_variance)) elemen dalam tensor menggunakan method serupa.

### Menemukan posisi maximum dan minimum

Bagaimana dengan menemukan posisi tensor di mana nilai maksimum terjadi?

Ini akan sangat berguna saat kalian ingin menyejajarkan label (katakanlah `['Green', 'Blue', 'Red']`) dengan prediction probabilities (kemungkinan prediksi) tensor kalian (Contohnya : `[0.98, 0.01, 0.01]`).

Dalam kasus ini, label yang diprediksi (yang memiliki probabilitas prediksi tertinggi) harusnya adalah `'Green'`.

Kalian juga dapat melakukan hal yang sama untuk minimum (jika diperlukan) dengan method berikut:
* [`tf.argmax()`](https://www.tensorflow.org/api_docs/python/tf/math/argmax) - menemukan posisi elemen maksimum dalam tensor tertentu.
* [`tf.argmin()`](https://www.tensorflow.org/api_docs/python/tf/math/argmin) - menemukan posisi elemen minimum dalam tensor tertentu.

In [ ]:
# Membuat tensor dengan 50 nilai antara 0 dan 1
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.958773  , 0.97976739, 0.16602717, 0.28731082, 0.49748596,
       0.34416077, 0.1372813 , 0.59153381, 0.90777781, 0.30332267,
       0.74772481, 0.77930641, 0.35020379, 0.42422401, 0.23792279,
       0.93467079, 0.05899115, 0.90129386, 0.45977715, 0.92678834,
       0.49420118, 0.72658676, 0.67365189, 0.42354097, 0.93269093,
       0.13385249, 0.52140009, 0.87661812, 0.12208627, 0.64137794,
       0.8696204 , 0.05513405, 0.83239878, 0.12993363, 0.04207118,
       0.64619237, 0.03415329, 0.20704967, 0.994277  , 0.72605277,
       0.0759561 , 0.58278865, 0.12794389, 0.6930628 , 0.30115236,
       0.482727  , 0.40193882, 0.93935914, 0.16357137, 0.39439121])>

In [ ]:
# Menemukan posisi elemen maximum dari F
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=38>

In [ ]:
# Menemukan posisi elemen minimum dari F
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=36>

In [ ]:
# Menemukan maximum element posisi F
print(f"Nilai maximum F ada pada posisi: {tf.argmax(F).numpy()}")
print(f"Nilai maximum F adalah: {tf.reduce_max(F).numpy()}")
print(f"Menggunakan tf.argmax() untuk indeks F, Nilai maximum F adalah: {F[tf.argmax(F)].numpy()}")
print(f"Apakah kedua nilai max-nya sama (seharusnya iya)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

Nilai maximum F ada pada posisi: 38
Nilai maximum F adalah: 0.9942770019503879
Menggunakan tf.argmax() untuk indeks F, Nilai maximum F adalah: 0.9942770019503879
Apakah kedua nilai max-nya sama (seharusnya iya)? True


### Squeezing a tensor (menghapus semua single dimensions)

Jika kalian perlu menghapus single-dimensions dari tensor (dimensi dengan ukuran 1), kalian bisa menggunakan `tf.squeeze()`.

* [`tf.squeeze()`](https://www.tensorflow.org/api_docs/python/tf/squeeze) - menghapus semua dimensi 1 dari tensor .


In [ ]:
# Membuat sebuah tensor dengan rank 5 (5 dimensi) tensor dari 50 nomor antara 0 dan 100
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [ ]:
# Squeeze tensor G (menghapus semua 1 dimensi)
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

### One-hot encoding

Jika kalian memiliki tensor indeks dan ingin menyandikannya satu kali / one-hot encoding (bertujuan untuk mengonversi data kategori menjadi data yang dienkripsi satu-per-satu), kalian dapat menggunakan [`tf.one_hot()`](https://www.tensorflow.org/api_docs/python/tf/one_hot).

Kalian juga harus menentukan parameter `depth` (yaitu tingkatan yang ingin kalian one-hot encode).

In [ ]:
# Membuat list index
some_list = [0, 1, 2, 3]

# Melakukan one-hot encode
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

Kalian juga dapat menentukan nilai untuk `on_value` dan `off_value` dibandingkan dengan `0` dan `1`.

In [ ]:
# Menentukan nilai khusus untuk on dan off encoding
tf.one_hot(some_list, depth=4, on_value="We're live!", off_value="Offline")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"We're live!", b'Offline', b'Offline', b'Offline'],
       [b'Offline', b"We're live!", b'Offline', b'Offline'],
       [b'Offline', b'Offline', b"We're live!", b'Offline'],
       [b'Offline', b'Offline', b'Offline', b"We're live!"]], dtype=object)>

### Squaring (kuadrat), log (logaritma), square root (akar kuadrat)

Banyak pula operasi matematika umum lainnya yang ingin anda lakukan pada tahap tertentu, yang mungkin ada.

Sekarang mari kita lihat:
* [`tf.square()`](https://www.tensorflow.org/api_docs/python/tf/math/square) - mendapatkan nilai kuadrat dari setiap nilai pada tensor.
* [`tf.sqrt()`](https://www.tensorflow.org/api_docs/python/tf/math/sqrt) - Mendapatkan nilai akar dari setiap nilai pada tensor (**catatan:** elemen pada tensor haruslah float atau method ini akan error).
* [`tf.math.log()`](https://www.tensorflow.org/api_docs/python/tf/math/log) - mendapatkan natural log (ln) dari setiap nilai pada tensor (elemen harus bertipe data float).

In [ ]:
# Membuat tensor baru
H = tf.constant(np.arange(1, 10))
H

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [ ]:
# Menguadratkan tensor tersebut
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [ ]:
# Menemukan akar kuadrat (akan menghasilkan error), harus bukan bilangan bulat (int)
tf.sqrt(H)

InvalidArgumentError: ignored

In [ ]:
# Mengubah tipe data H menjadi float32
H = tf.cast(H, dtype=tf.float32)
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [ ]:
# Menemukan akar kuadrat
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
# Menemukan log (input juga harus bertipe data float)
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Memanipulasi `tf.Variable` tensor

Elemen tensor yang dibuat dengan `tf.Variable()` dapat diganti atau diubah dengan method seperti:

* [`.assign()`](https://www.tensorflow.org/api_docs/python/tf/Variable#assign) - menetapkan nilai yang berbeda ke indeks tertentu dari variabel tensor.
* [`.add_assign()`](https://www.tensorflow.org/api_docs/python/tf/Variable#assign_add) - melakukan operasi penjumlahan ke nilai yang ada dan menetapkan kembali pada indeks tensor variabel tertentu.


In [ ]:
# Membuat Variable tensor
I = tf.Variable(np.arange(0, 5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [ ]:
# Menetapkan nilai akhir pada tensor menjadi nilai baru yaitu 50
I.assign([0, 1, 2, 3, 50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [ ]:
# Perubahan terjadi pada indeks terakhir (nilai terkhir sekarang 50, bukan 4)
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [ ]:
# Menambahkan 10 (I + 10) ke setiap elemen di I
I.assign_add([10, 10, 10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

In [ ]:
# Sekali lagi, perubahan terjadi
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

## Tensors dan NumPy

Kita sudah melihat sebelumnya bagaimana beberapa tensor berinteraksi dengan NumPy arrays, seperti, menggunakan NumPy arrays untuk membuat tensor tensors.

Tensor juga dapat dikonversi ke NumPy arrays menggunakan:

* `np.array()` - meneruskan tensor untuk mengonversinya menjadi ndarray (tipe data utama NumPy).
* `tensor.numpy()` - memanggil tensor dan mengonversi ke ndarray.

Melakukan hal ini akan sangat membantu karena membuat tensor menjadi iterable (dapatndiubah) serta memungkinkan kita menggunakan salah satu method NumPy pada tensor tersebut.

In [ ]:
# Membaut tensor dari NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Mengonversi tensor J menjadi NumPy dengan np.array()
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# Mengonversi tensor J menjadi NumPy dengan .numpy()
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

Secara bawaan tensor memiliki tipe data `dtype=float32`, yang dimana NumPy arrays memiliki tipe data `dtype=float64`.

Hal ini dikarenakan neural networks (yang biasanya dibangun dengan TensorFlow) umumnya dapat bekerja sangat baik walau dengan presisi yang lebih sedikit (32-bit lebih baik daripada 64-bit).

In [ ]:
# Membuat tensor dari NumPy dan dari array
numpy_J = tf.constant(np.array([3., 7., 10.])) # tipe data akan menjadi float64 (karena NumPy)
tensor_J = tf.constant([3., 7., 10.]) # tipe data akan menjadi float32 (karena menjadi tipe data bawaan TensorFlow)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

## Menggunakan `@tf.function`

Dalam perjalanan kalian mengeksplore TensorFlow, kalian mungkin menemukan fungsi Python yang memiliki dekorator [`@tf.function`](https://www.tensorflow.org/api_docs/python/tf/function).

Jika kalian tidak yakin aoa itu dekorator pada Python, [bacalah RealPython's guide untuk dekorator](https://realpython.com/primer-on-python-decorators/).

Namun singkatnya, decorators memodifikasi fungsi dengan satu atau cara yang lain.

Dalam `@tf.function` decorator case, hal itu mengubah funsi Python menjadi grafik TensorFlow. Yang merupakan cara keren untuk mengatakan, jika kalian membuat kode Python kalian sendiri, dan kalian decorate itu dengan `@tf.function`, ketika kalian export kode kalian (untuk berpotensi dijalankan di perangkat lain), TensorFlow akan mencoba menggubahnya menjadi versi yang lebih cepat dari dirinya sendiri (dengan menjadikannya bagian dari komputasi grafis / GPU).

Untuk lebih lanjut tentang ini, bacalah panduan berikut [Better performnace with tf.function](https://www.tensorflow.org/guide/function).

In [ ]:
# Membuat fungsi yang sederhana
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [ ]:
# Membuat fungsi yang sama dan decorate dengan tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

Jika kalian melihat tidak ada perbedaan antara dua fungsi diatas (yang decorated  dan yang non-decorated) kalian benar.

Banyak perbedaan terjadi di belakang layar. Ssalah satu yang utama adalah percepatan kode potensial jika memungkinkan.

## Menemukan cara untuk mengakses GPUs

Kita telah sering menyebutkan GPU di hampir seluruh notebook (hands-on) ini.

Jadi, bagaimana kita memeriksa apakah kita dapat mengaksesnya?

Kalian dapat memeriksanya apakah memiliki akses ke GPU dengan [`tf.config.list_physical_devices()`](https://www.tensorflow.org/guide/gpu).

In [ ]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


Jika di atas menampilkan array kosong (atau tidak sama sekali), itu berarti komputer kalian tidak dapat menemukannya (atau setidaknya TensorFlow tidak dapat menemukannya).

Jika kalian running dengan menggunakan Google Colab, kalian bisa mengakses GPU dengan membuka *Runtime -> Change Runtime Type -> Select GPU* (**catatan:** setelah kalian melakukannya, maka notebook akan di restart dan variable dan sesi yang telah tersimpan akan hilang).

Setelah anda mengubah tipe runtime anda, jalankan cell dibawah.

In [ ]:
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


Jika kalian mendapatkan akses ke GPU, cell yang ada diatas harusnya memberikan output seperti:

`[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]`

Kalian juga bisa menemukan informasi tentang GPU kalian dengan menggunakan  `!nvidia-smi`.

In [ ]:
!nvidia-smi

Wed May 24 10:20:19 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P0    26W /  70W |    375MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

> 🔑 **Catatan:** Jika kalian mempunyai akses ke GPU, TensorFlow akan otomatis menggunakannya bila memungkinkan.

## 🛠 Latihan

1. Buat vector, scalar, matrix dan tensor dengan values (nilai) pilihan kalian dengan menggunakan `tf.constant()`.
2. Temukan shape, rank dan size dari tensor yang anda buat dari latihan 1.
3. Buatlah dua tensor yang berisi random values (nilai acak) antara 0 dan 1 dengan shape `[5, 300]`.
4. Kalikan dua tensor yang kalian buat di latihan 3 menggunakan matrix multiplication.
5. Kalikan dua tensor yang kalian buat di latihan 3 menggunakan dot product.
6. Buatlah tensor dengan random values (nilai acak) antara 0 dan 1 dengan shape `[224, 224, 3]`.
7. Temukanlah min dan max values dari tensor yang kalian buat dalam latihan 6.
8. Buatlah tensor dengan random values dan memiliki shape `[1, 224, 224, 3]` lalu squeeze tensor untuk mengganti shape menjadi `[224, 224, 3]`.
9. Buatlah tensor dengan shape `[10]` menggunakan nilai pilihan kalian sendiri, lalu cari indeks yang memiliki nilai maksimum.
10. One-hot encode tensor yang kalian buat pada latihan 9.

## 📖 Extra-curriculum (Pembelajaran Tambahan)

* Baca [list of TensorFlow Python APIs](https://www.tensorflow.org/api_docs/python/), pilih salah satu yang belum kami bahas, reverse engineer itu (tulis sendiri kode dokumentasinya) dan cari tahu apa fungsinya.
* Cobalah untuk membuat rangkaian fungsi tensor untuk menghitung tagihan belanjaan terbaru kalian (tidak apa-apa jika kalian tidak menggunakan nama barang, hanya harga dalam bentuk numerik).
  * Bagaimana kalian menghitung tagihan belanjaan untuk bulan dan tahun menggunakan tensor?
* Ikuti tutorial [TensorFlow 2.x quick start for beginners](https://www.tensorflow.org/tutorials/quickstart/beginner) (pastikan untuk mengetiknya sendiri semua kodenya, meskipun kalian tidak memahaminya).
  * Apakah ada fungsi yang kami gunakan di sini yang cocok dengan yang digunakan di sana? Yang mana yang sama? Mana yang belum pernah kalian lihat sebelumnya?
* Tonton video ["What's a tensor?"](https://www.youtube.com/watch?v=f5liqUk0ZTw) - pengantar visual yang bagus untuk banyak konsep yang telah di bahas pada notebook ini.